help([==[

Description
===========
bcl2fastq Conversion Software both demultiplexes data and converts BCL files generated by
 Illumina sequencing systems to standard FASTQ file formats for downstream analysis.


More information
================
 - Homepage: https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html
]==])

whatis([==[Description: bcl2fastq Conversion Software both demultiplexes data and converts BCL files generated by
 Illumina sequencing systems to standard FASTQ file formats for downstream analysis.]==])
whatis([==[Homepage: https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html]==])

local root = "/app/software/bcl2fastq2/2.20.0-foss-2018b"

conflict("bcl2fastq2")

if not isloaded("foss/2018b") then
    load("foss/2018b")
end

if not isloaded("zlib/1.2.11-GCCcore-7.3.0") then
    load("zlib/1.2.11-GCCcore-7.3.0")
end

prepend_path("LD_LIBRARY_PATH", pathJoin(root, "lib"))
prepend_path("LIBRARY_PATH", pathJoin(root, "lib"))
prepend_path("PATH", pathJoin(root, "bin"))
setenv("EBROOTBCL2FASTQ2", root)
setenv("EBVERSIONBCL2FASTQ2", "2.20.0")
setenv("EBDEVELBCL2FASTQ2", pathJoin(root, "/app/logs/bcl2fastq2-2.20.0-foss-2018b-easybuild-devel"))

-- Built with EasyBuild version 3.8.0
